/**
 * FOINWI Daily Intelligence — educational insight catalog (30+).
 * Concise beginner-friendly notes. No product or return guarantees.
 */

import { createInsight, EDUCATIONAL_NOTICE } from "./insightTypes.js";

export const DAILY_INSIGHTS = [
  createInsight({
    id: "insight-savings-pay-yourself",
    title: "Pay yourself first, then spend",
    summary: "Moving a small amount to savings before other spending builds the habit.",
    explanation:
      "Many beginners find it easier to save when the transfer happens early in the month. Even a modest automatic transfer can make saving intentional rather than leftover-based.",
    conceptId: "savings",
    category: "savings",
    difficulty: "beginner",
    tags: ["savings", "habits", "cash-flow"],
    relatedCalculatorPaths: ["/goal-planner", "/rd-calculator"],
    relatedLessonSlugs: ["money-basics", "saving-budgeting"],
    relatedJourneySlugs: ["build-wealth"],
    relatedMissionSlugs: ["build-wealth"],
  }),
  createInsight({
    id: "insight-savings-consistency",
    title: "Consistency often matters more than size",
    summary: "Regular small savings can matter more than occasional large deposits.",
    explanation:
      "A steady monthly habit is easier to sustain than waiting for a bonus. Tracking progress over months helps you see whether your saving rhythm matches your goals.",
    conceptId: "savings",
    category: "savings",
    difficulty: "beginner",
    tags: ["savings", "discipline", "habits"],
    relatedCalculatorPaths: ["/goal-planner", "/sip-calculator"],
    relatedLessonSlugs: ["saving-budgeting"],
    relatedJourneySlugs: ["build-wealth"],
    relatedMissionSlugs: ["build-wealth"],
  }),
  createInsight({
    id: "insight-budgeting-categories",
    title: "A simple budget starts with three buckets",
    summary: "Needs, wants, and savings are enough categories to begin.",
    explanation:
      "You do not need a complex spreadsheet on day one. Separating essential costs, discretionary spending, and savings gives a clear picture of where money goes each month.",
    conceptId: "budgeting",
    category: "savings",
    difficulty: "beginner",
    tags: ["budgeting", "expenses", "planning"],
    relatedCalculatorPaths: ["/goal-planner"],
    relatedLessonSlugs: ["saving-budgeting", "money-basics"],
    relatedJourneySlugs: ["build-wealth", "become-debt-free"],
    relatedMissionSlugs: ["become-debt-free"],
  }),
  createInsight({
    id: "insight-budgeting-track",
    title: "Track for one week before you cut",
    summary: "Observing spending first makes later changes more realistic.",
    explanation:
      "Cutting categories without knowing current habits often fails. A short tracking period reveals patterns — subscriptions, food delivery, or transport — that you can adjust thoughtfully.",
    conceptId: "budgeting",
    category: "savings",
    difficulty: "beginner",
    tags: ["budgeting", "tracking", "habits"],
    relatedCalculatorPaths: ["/goal-planner"],
    relatedLessonSlugs: ["saving-budgeting"],
    relatedJourneySlugs: ["become-debt-free"],
    relatedMissionSlugs: ["become-debt-free"],
  }),
  createInsight({
    id: "insight-emergency-buffer",
    title: "An emergency buffer comes before ambitious goals",
    summary: "A dedicated reserve helps handle surprises without disrupting long-term plans.",
    explanation:
      "Many educational guides discuss three to six months of essential costs as a starting reference. Keeping this money separate from long-term investments reduces the need to sell assets during a cash crunch.",
    conceptId: "emergency-fund",
    category: "protection",
    difficulty: "beginner",
    tags: ["emergency-fund", "liquidity", "safety"],
    relatedCalculatorPaths: ["/goal-planner", "/fd-calculator"],
    relatedLessonSlugs: ["saving-budgeting", "insurance-planning"],
    relatedJourneySlugs: ["protect-your-family"],
    relatedMissionSlugs: ["protect-your-family"],
  }),
  createInsight({
    id: "insight-emergency-separate",
    title: "Keep emergency money easy to reach",
    summary: "Liquidity matters as much as the amount you set aside.",
    explanation:
      "An emergency fund is meant for unexpected expenses. Parking it in a place you can access quickly — while still keeping it distinct from everyday spending — supports that purpose.",
    conceptId: "emergency-fund",
    category: "protection",
    difficulty: "beginner",
    tags: ["emergency-fund", "liquidity", "fd"],
    relatedCalculatorPaths: ["/fd-calculator", "/rd-calculator"],
    relatedLessonSlugs: ["saving-budgeting"],
    relatedJourneySlugs: ["protect-your-family", "build-wealth"],
    relatedMissionSlugs: ["protect-your-family"],
  }),
  createInsight({
    id: "insight-compounding-time",
    title: "Time is a quiet partner of compounding",
    summary: "Starting earlier gives returns more years to compound on themselves.",
    explanation:
      "Compounding means earning returns on both principal and earlier gains. Educational examples often show that longer timelines can matter as much as the contribution amount.",
    conceptId: "compounding",
    category: "investing",
    difficulty: "beginner",
    tags: ["compounding", "time", "growth"],
    relatedCalculatorPaths: ["/compound-interest-calculator", "/sip-calculator", "/cagr-calculator"],
    relatedLessonSlugs: ["investing-fundamentals", "money-basics"],
    relatedJourneySlugs: ["build-wealth"],
    relatedMissionSlugs: ["build-wealth"],
  }),
  createInsight({
    id: "insight-compounding-patience",
    title: "Compounding rewards patience more than timing tricks",
    summary: "Staying invested through ordinary market ups and downs supports compounding.",
    explanation:
      "Frequent stopping and restarting can interrupt the compounding process. Educational materials emphasise understanding volatility as a normal part of long-term growth discussions — not as a signal to chase short-term moves.",
    conceptId: "compounding",
    category: "investing",
    difficulty: "intermediate",
    tags: ["compounding", "discipline", "long-term"],
    relatedCalculatorPaths: ["/sip-calculator", "/cagr-calculator"],
    relatedLessonSlugs: ["investing-fundamentals", "mutual-funds-sip"],
    relatedJourneySlugs: ["build-wealth", "retirement-planning"],
    relatedMissionSlugs: ["build-wealth"],
  }),
  createInsight({
    id: "insight-sip-regular",
    title: "SIP is about rhythm, not perfection",
    summary: "A fixed monthly amount spreads purchases across different market levels.",
    explanation:
      "A Systematic Investment Plan invests a set amount at regular intervals. Educational discussions often highlight rupee-cost averaging and habit-building — not guarantees of higher returns.",
    conceptId: "sip",
    category: "investing",
    difficulty: "beginner",
    tags: ["sip", "mutual-funds", "discipline"],
    relatedCalculatorPaths: ["/sip-calculator", "/goal-planner", "/cagr-calculator"],
    relatedLessonSlugs: ["mutual-funds-sip", "investing-fundamentals"],
    relatedJourneySlugs: ["build-wealth"],
    relatedMissionSlugs: ["build-wealth"],
  }),
  createInsight({
    id: "insight-sip-goals",
    title: "Link SIP amounts to a clear goal",
    summary: "A target date and corpus make monthly contributions easier to evaluate.",
    explanation:
      "Without a goal, it is hard to know whether a SIP amount is enough. Goal planners help translate a future need into an estimated monthly contribution for educational planning.",
    conceptId: "sip",
    category: "investing",
    difficulty: "beginner",
    tags: ["sip", "goals", "planning"],
    relatedCalculatorPaths: ["/goal-planner", "/sip-calculator"],
    relatedLessonSlugs: ["mutual-funds-sip"],
    relatedJourneySlugs: ["build-wealth", "child-education"],
    relatedMissionSlugs: ["build-wealth"],
  }),
  createInsight({
    id: "insight-mf-basics",
    title: "Mutual funds pool money across many investors",
    summary: "One fund can hold a mix of stocks, bonds, or other assets.",
    explanation:
      "Mutual funds let investors participate in diversified portfolios without picking every security themselves. Understanding fund type — equity, debt, or hybrid — is a useful first step before comparing options.",
    conceptId: "mutual-funds",
    category: "investing",
    difficulty: "beginner",
    tags: ["mutual-funds", "diversification", "nav"],
    relatedCalculatorPaths: ["/sip-calculator", "/lumpsum-calculator", "/cagr-calculator"],
    relatedLessonSlugs: ["mutual-funds-sip", "investing-fundamentals"],
    relatedJourneySlugs: ["build-wealth"],
    relatedMissionSlugs: ["build-wealth"],
  }),
  createInsight({
    id: "insight-mf-costs",
    title: "Expense ratios quietly affect long-term outcomes",
    summary: "Fund costs reduce the return that compounds over time.",
    explanation:
      "Even small annual fees add up across years. Educational reviews of mutual funds often include checking expense ratios alongside risk level and investment objective.",
    conceptId: "mutual-funds",
    category: "investing",
    difficulty: "intermediate",
    tags: ["mutual-funds", "costs", "long-term"],
    relatedCalculatorPaths: ["/cagr-calculator", "/sip-calculator"],
    relatedLessonSlugs: ["mutual-funds-sip"],
    relatedJourneySlugs: ["build-wealth"],
    relatedMissionSlugs: ["build-wealth"],
  }),
  createInsight({
    id: "insight-inflation-real",
    title: "Inflation shrinks what money can buy",
    summary: "A rupee today usually buys more than the same rupee years later.",
    explanation:
      "Inflation is the rise in prices over time. When planning goals or retirement, educational tools often compare nominal growth with inflation-adjusted — or “real” — purchasing power.",
    conceptId: "inflation",
    category: "planning",
    difficulty: "beginner",
    tags: ["inflation", "purchasing-power", "goals"],
    relatedCalculatorPaths: ["/inflation-calculator", "/retirement-calculator", "/goal-planner"],
    relatedLessonSlugs: ["money-basics", "retirement-planning"],
    relatedJourneySlugs: ["retirement-planning", "child-education"],
    relatedMissionSlugs: ["retirement-planning"],
  }),
  createInsight({
    id: "insight-inflation-goals",
    title: "Build future costs into goal estimates",
    summary: "Education and lifestyle costs often rise faster than general prices.",
    explanation:
      "Using today’s fee for a college goal ten years away can understate the need. An inflation calculator helps explore how higher future costs change the monthly savings estimate.",
    conceptId: "inflation",
    category: "planning",
    difficulty: "intermediate",
    tags: ["inflation", "education", "planning"],
    relatedCalculatorPaths: ["/inflation-calculator", "/goal-planner", "/sip-calculator"],
    relatedLessonSlugs: ["retirement-planning", "money-basics"],
    relatedJourneySlugs: ["child-education", "retirement-planning"],
    relatedMissionSlugs: ["child-education"],
  }),
  createInsight({
    id: "insight-fd-basics",
    title: "Fixed deposits offer predictable maturity values",
    summary: "An FD locks money for a tenure at a stated interest rate.",
    explanation:
      "Fixed deposits are commonly used for short- to medium-term parking of money when predictability matters. Educational comparisons often weigh FD returns against inflation and liquidity needs.",
    conceptId: "fd",
    category: "savings",
    difficulty: "beginner",
    tags: ["fd", "fixed-deposit", "safety"],
    relatedCalculatorPaths: ["/fd-calculator", "/compound-interest-calculator"],
    relatedLessonSlugs: ["money-basics", "saving-budgeting"],
    relatedJourneySlugs: ["protect-your-family", "build-wealth"],
    relatedMissionSlugs: ["protect-your-family"],
  }),
  createInsight({
    id: "insight-rd-habits",
    title: "Recurring deposits build saving discipline",
    summary: "An RD deposits a fixed amount every month for a set tenure.",
    explanation:
      "Recurring deposits suit beginners who want a scheduled saving habit with a known maturity date. They are often discussed alongside emergency buffers and short-term goals.",
    conceptId: "rd",
    category: "savings",
    difficulty: "beginner",
    tags: ["rd", "habits", "monthly"],
    relatedCalculatorPaths: ["/rd-calculator", "/goal-planner"],
    relatedLessonSlugs: ["saving-budgeting", "money-basics"],
    relatedJourneySlugs: ["build-wealth"],
    relatedMissionSlugs: ["build-wealth"],
  }),
  createInsight({
    id: "insight-ppf-longterm",
    title: "PPF is a long-horizon government-backed option",
    summary: "Public Provident Fund has a 15-year lock-in and tax-related features.",
    explanation:
      "PPF is frequently discussed in Indian tax and retirement education. The long lock-in means it fits goals measured in years, not months — and contribution limits apply each year.",
    conceptId: "ppf",
    category: "investing",
    difficulty: "intermediate",
    tags: ["ppf", "80c", "long-term"],
    relatedCalculatorPaths: ["/ppf-calculator", "/goal-planner"],
    relatedLessonSlugs: ["income-tax-basics", "retirement-planning"],
    relatedJourneySlugs: ["save-tax", "retirement-planning"],
    relatedMissionSlugs: ["save-tax"],
  }),
  createInsight({
    id: "insight-epf-salary",
    title: "EPF grows with salary contributions over a career",
    summary: "Employee Provident Fund builds a retirement corpus through payroll deductions.",
    explanation:
      "EPF combines employee and employer contributions for many salaried workers. Educational calculators help estimate how contribution rate and years of service may shape the projected corpus.",
    conceptId: "epf",
    category: "planning",
    difficulty: "intermediate",
    tags: ["epf", "salary", "retirement"],
    relatedCalculatorPaths: ["/epf-calculator", "/retirement-calculator"],
    relatedLessonSlugs: ["retirement-planning"],
    relatedJourneySlugs: ["retirement-planning"],
    relatedMissionSlugs: ["retirement-planning"],
  }),
  createInsight({
    id: "insight-nps-voluntary",
    title: "NPS is a voluntary retirement building block",
    summary: "National Pension System lets you contribute toward a long-term retirement corpus.",
    explanation:
      "NPS is often studied alongside EPF and other retirement tools. Educational overviews cover contribution flexibility, asset allocation choices, and withdrawal rules — without recommending any specific fund manager.",
    conceptId: "nps",
    category: "planning",
    difficulty: "intermediate",
    tags: ["nps", "pension", "retirement"],
    relatedCalculatorPaths: ["/nps-calculator", "/retirement-calculator", "/swp-calculator"],
    relatedLessonSlugs: ["retirement-planning"],
    relatedJourneySlugs: ["retirement-planning"],
    relatedMissionSlugs: ["retirement-planning"],
  }),
  createInsight({
    id: "insight-tax-regimes",
    title: "Old and New tax regimes change deduction math",
    summary: "Comparing regimes helps you see which structure fits your income pattern.",
    explanation:
      "India’s income tax education often starts with Old vs New regime differences. Calculators can approximate liability under each — educational estimates only, not filing advice.",
    conceptId: "tax",
    category: "tax",
    difficulty: "intermediate",
    tags: ["tax", "regime", "salary"],
    relatedCalculatorPaths: ["/income-tax-calculator", "/hra-calculator", "/ppf-calculator"],
    relatedLessonSlugs: ["income-tax-basics"],
    relatedJourneySlugs: ["save-tax"],
    relatedMissionSlugs: ["save-tax"],
  }),
  createInsight({
    id: "insight-tax-80c",
    title: "Section 80C is one piece of tax education",
    summary: "Several instruments are commonly discussed under 80C limits.",
    explanation:
      "PPF, ELSS, life insurance premiums, and certain other items appear in 80C educational lists. Understanding the overall limit and lock-ins matters before treating any instrument as purely a tax tool.",
    conceptId: "tax",
    category: "tax",
    difficulty: "intermediate",
    tags: ["tax", "80c", "deductions"],
    relatedCalculatorPaths: ["/ppf-calculator", "/income-tax-calculator"],
    relatedLessonSlugs: ["income-tax-basics"],
    relatedJourneySlugs: ["save-tax"],
    relatedMissionSlugs: ["save-tax"],
  }),
  createInsight({
    id: "insight-hra-basics",
    title: "HRA exemption depends on rent and salary structure",
    summary: "House Rent Allowance rules use the lowest of a few defined calculations.",
    explanation:
      "HRA education usually covers basic salary, rent paid, and city category. An HRA calculator helps explore how those inputs change the exempt and taxable portions — for learning, not payroll instructions.",
    conceptId: "tax",
    category: "tax",
    difficulty: "intermediate",
    tags: ["hra", "tax", "salary"],
    relatedCalculatorPaths: ["/hra-calculator", "/income-tax-calculator"],
    relatedLessonSlugs: ["income-tax-basics"],
    relatedJourneySlugs: ["save-tax"],
    relatedMissionSlugs: ["save-tax"],
  }),
  createInsight({
    id: "insight-insurance-purpose",
    title: "Insurance is for protection, not returns",
    summary: "Cover is meant to reduce financial damage from defined risks.",
    explanation:
      "Educational guides separate protection products from investment products. Term life and health cover are commonly discussed as ways to protect family cash flow — not as wealth-building tools.",
    conceptId: "insurance",
    category: "protection",
    difficulty: "beginner",
    tags: ["insurance", "protection", "family"],
    relatedCalculatorPaths: ["/goal-planner"],
    relatedLessonSlugs: ["insurance-planning"],
    relatedJourneySlugs: ["protect-your-family"],
    relatedMissionSlugs: ["protect-your-family"],
  }),
  createInsight({
    id: "insight-loans-total-cost",
    title: "Look at total interest, not only the EMI",
    summary: "A comfortable EMI can still mean a large interest bill over time.",
    explanation:
      "EMI spreads repayment into equal monthly amounts. Educational loan reviews compare tenure, rate, and total interest so borrowers see the full cost — not just the monthly cash outflow.",
    conceptId: "emi",
    category: "debt",
    difficulty: "beginner",
    tags: ["emi", "loans", "interest"],
    relatedCalculatorPaths: ["/emi-calculator", "/loan-prepayment-calculator"],
    relatedLessonSlugs: ["loans-emi"],
    relatedJourneySlugs: ["become-debt-free", "buy-dream-home"],
    relatedMissionSlugs: ["become-debt-free"],
  }),
  createInsight({
    id: "insight-emi-affordability",
    title: "EMI should leave room for other goals",
    summary: "High EMI ratios can crowd out saving and emergency buffers.",
    explanation:
      "Educational affordability checks often ask whether EMI plus essential costs still leave space for savings. Stress-testing EMI at a slightly higher rate is a common learning exercise before committing to a long loan.",
    conceptId: "emi",
    category: "debt",
    difficulty: "beginner",
    tags: ["emi", "affordability", "cash-flow"],
    relatedCalculatorPaths: ["/emi-calculator", "/home-loan-eligibility-calculator"],
    relatedLessonSlugs: ["loans-emi"],
    relatedJourneySlugs: ["buy-dream-home", "buy-your-car"],
    relatedMissionSlugs: ["buy-dream-home"],
  }),
  createInsight({
    id: "insight-debt-priority",
    title: "List every debt before choosing a payoff order",
    summary: "Balances, rates, and tenure together shape a repayment plan.",
    explanation:
      "Debt management education usually starts with a full inventory. Some learners prioritise high-interest balances; others prefer small balances for momentum. Either approach works better with clear numbers.",
    conceptId: "debt",
    category: "debt",
    difficulty: "beginner",
    tags: ["debt", "repayment", "planning"],
    relatedCalculatorPaths: ["/emi-calculator", "/loan-prepayment-calculator", "/goal-planner"],
    relatedLessonSlugs: ["loans-emi"],
    relatedJourneySlugs: ["become-debt-free"],
    relatedMissionSlugs: ["become-debt-free"],
  }),
  createInsight({
    id: "insight-debt-prepay",
    title: "Prepayment reduces principal — and future interest",
    summary: "Extra payments early in a loan can cut total interest paid.",
    explanation:
      "When you prepay, outstanding principal falls, so future interest is calculated on a smaller amount. Educational prepayment calculators help compare tenure reduction versus EMI reduction scenarios.",
    conceptId: "debt",
    category: "debt",
    difficulty: "intermediate",
    tags: ["debt", "prepayment", "interest"],
    relatedCalculatorPaths: ["/loan-prepayment-calculator", "/emi-calculator"],
    relatedLessonSlugs: ["loans-emi"],
    relatedJourneySlugs: ["become-debt-free", "buy-dream-home"],
    relatedMissionSlugs: ["become-debt-free"],
  }),
  createInsight({
    id: "insight-retirement-corpus",
    title: "Retirement planning starts with a corpus estimate",
    summary: "How much you may need depends on lifestyle, inflation, and longevity.",
    explanation:
      "Educational retirement tools estimate a target corpus and then explore how EPF, NPS, SIPs, and withdrawals might contribute. These are planning sketches — not promises of a specific outcome.",
    conceptId: "retirement",
    category: "planning",
    difficulty: "intermediate",
    tags: ["retirement", "corpus", "inflation"],
    relatedCalculatorPaths: ["/retirement-calculator", "/nps-calculator", "/epf-calculator", "/swp-calculator"],
    relatedLessonSlugs: ["retirement-planning"],
    relatedJourneySlugs: ["retirement-planning"],
    relatedMissionSlugs: ["retirement-planning"],
  }),
  createInsight({
    id: "insight-retirement-inflation",
    title: "Retirement income must keep up with rising costs",
    summary: "Inflation can quietly erode purchasing power over a long retirement.",
    explanation:
      "A fixed monthly income that feels comfortable today may buy less in twenty years. Educational retirement lessons often pair corpus estimates with inflation assumptions and withdrawal concepts like SWP.",
    conceptId: "retirement",
    category: "planning",
    difficulty: "intermediate",
    tags: ["retirement", "inflation", "swp"],
    relatedCalculatorPaths: ["/inflation-calculator", "/retirement-calculator", "/swp-calculator"],
    relatedLessonSlugs: ["retirement-planning", "money-basics"],
    relatedJourneySlugs: ["retirement-planning"],
    relatedMissionSlugs: ["retirement-planning"],
  }),
  createInsight({
    id: "insight-goals-smart",
    title: "Clear goals turn vague wishes into plans",
    summary: "Amount, date, and monthly capacity make a goal measurable.",
    explanation:
      "Goal planning education breaks a target into timeline and contribution estimates. Whether the goal is a home down payment or education corpus, numbers make trade-offs visible.",
    conceptId: "goal-planning",
    category: "planning",
    difficulty: "beginner",
    tags: ["goals", "planning", "sip"],
    relatedCalculatorPaths: ["/goal-planner", "/sip-calculator", "/inflation-calculator"],
    relatedLessonSlugs: ["money-basics", "saving-budgeting"],
    relatedJourneySlugs: ["build-wealth", "child-education", "buy-dream-home"],
    relatedMissionSlugs: ["child-education"],
  }),
  createInsight({
    id: "insight-habits-review",
    title: "A quarterly money review beats a yearly panic",
    summary: "Short, regular check-ins keep goals and spending aligned.",
    explanation:
      "Financial habits improve when reviews are small and frequent. Checking savings rate, EMI burden, and goal progress once a quarter is an educational practice many beginners can sustain.",
    conceptId: "savings",
    category: "habits",
    difficulty: "beginner",
    tags: ["habits", "review", "discipline"],
    relatedCalculatorPaths: ["/goal-planner"],
    relatedLessonSlugs: ["money-basics", "saving-budgeting"],
    relatedJourneySlugs: ["build-wealth"],
    relatedMissionSlugs: ["build-wealth"],
  }),
  createInsight({
    id: "insight-habits-automate",
    title: "Automation reduces the need for willpower",
    summary: "Scheduled transfers make saving and investing less dependent on mood.",
    explanation:
      "When contributions move automatically on payday, you are less likely to skip them. Educational habit-building often pairs automation with a simple monthly budget check.",
    conceptId: "budgeting",
    category: "habits",
    difficulty: "beginner",
    tags: ["habits", "automation", "sip"],
    relatedCalculatorPaths: ["/sip-calculator", "/rd-calculator", "/goal-planner"],
    relatedLessonSlugs: ["saving-budgeting", "mutual-funds-sip"],
    relatedJourneySlugs: ["build-wealth"],
    relatedMissionSlugs: ["build-wealth"],
  }),
  createInsight({
    id: "insight-credit-score",
    title: "Credit score reflects repayment behaviour over time",
    summary: "On-time payments and utilisation patterns influence score discussions.",
    explanation:
      "Credit score education covers repayment history, credit utilisation, and account mix. A healthier score can affect loan access and terms — it is a report card, not a wealth measure.",
    conceptId: "credit-score",
    category: "debt",
    difficulty: "beginner",
    tags: ["credit-score", "loans", "repayment"],
    relatedCalculatorPaths: ["/emi-calculator", "/home-loan-eligibility-calculator"],
    relatedLessonSlugs: ["loans-emi"],
    relatedJourneySlugs: ["become-debt-free", "buy-your-car"],
    relatedMissionSlugs: ["become-debt-free"],
  }),
  createInsight({
    id: "insight-asset-allocation",
    title: "Allocation spreads risk across asset types",
    summary: "Equity, debt, and cash play different roles in a long-term plan.",
    explanation:
      "Asset allocation education focuses on mixing growth and stability based on goals and time horizon. Rebalancing occasionally brings the mix back toward your chosen proportions.",
    conceptId: "asset-allocation",
    category: "investing",
    difficulty: "intermediate",
    tags: ["allocation", "diversification", "risk"],
    relatedCalculatorPaths: ["/sip-calculator", "/ppf-calculator", "/fd-calculator"],
    relatedLessonSlugs: ["investing-fundamentals", "mutual-funds-sip"],
    relatedJourneySlugs: ["build-wealth", "retirement-planning"],
    relatedMissionSlugs: ["build-wealth"],
  }),
].map((insight) => ({
  ...insight,
  educationalNotice: EDUCATIONAL_NOTICE,
}));

export const INSIGHT_BY_ID = Object.fromEntries(
  DAILY_INSIGHTS.map((insight) => [insight.id, insight]),
);

export function getAllDailyInsights() {
  return DAILY_INSIGHTS;
}

export function getInsightCatalogCount() {
  return DAILY_INSIGHTS.length;
}
